# Generated by Django 3.2.12 on 2022-05-20 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='company',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='country',
        ),
        migrations.AddField(
            model_name='movie',
            name='company',
            field=models.ManyToManyField(related_name='movies', to='movies.Company'),
        ),
        migrations.AddField(
            model_name='movie',
            name='country',
            field=models.ManyToManyField(related_name='movies', to='movies.Country'),
        ),
    ]
